# Generated by Django 4.0.1 on 2022-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('DOLL', 'DOLL'), ('EURO', 'EURO')], default='BYN', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
