# Generated by Django 4.0.1 on 2022-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_post_post_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_cats',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
