# Generated by Django 4.0.1 on 2022-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_post_post_cats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_info',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_cats',
        ),
        migrations.AddField(
            model_name='post',
            name='cats',
            field=models.CharField(choices=[("men's", "Men's"), ("women's", "Women's"), ("children's", "Children's")], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Минск', 'минск'), ('Брест', 'брест'), ('Гродно', 'гродно'), ('Гомель', 'гомель'), ('Витебск', 'витебск'), ('Могилев', 'могилев')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
