# Generated by Django 4.0.1 on 2022-01-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_rename_post_date_post_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cats',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Минск', 'минск'), ('Брест', 'брест'), ('Гродно', 'гродно'), ('Гомель', 'гомель'), ('Витебск', 'витебск'), ('Могилев', 'могилев')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='goods.Category'),
        ),
    ]
