# Generated by Django 4.0.1 on 2022-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_category_rename_cats_post_category_alter_post_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
