# Generated by Django 4.0.1 on 2022-01-15 17:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_remove_category_parent_id_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('1', 'Минск'), ('2', 'Брест'), ('3', 'Гродно'), ('4', 'Гомель'), ('5', 'Витебск'), ('6', 'Могилев')], default='', max_length=10),
        ),
    ]
