# Generated by Django 4.0.1 on 2022-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Минск', 'Минск'), ('Брест', 'Брест'), ('Гродно', 'Гродно'), ('Гомель', 'Гомель'), ('Витебск', 'Витебск'), ('Могилев', 'Могилев')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=255, verbose_name='URL'),
        ),
    ]
